# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in ms)
command_timeout = 5000

# Battery: shows how charged the device's battery is and its current charging
# status. The module is only visible when the device's battery is below 10%.
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 20
style = "bold red"

# Shows a character beside where the text is entered in the terminal
[character]
success_symbol = "[Êƒ](bold green) "
error_symbol = "[âœ—](bold red) "
vicmd_symbol = "[V](bold blue) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
# Show at most the current and parent directory
truncation_length = 1
# Don't override the truncation length when in a git repo
truncate_to_repo = false
# Show that we're in a truncated dir
truncation_symbol = "â€¦/"

[git_status]
# Use this (Linux) path to a Windows Starship executable to render git_status
# when on Windows paths in WSL
windows_starship = "/mnt/c/Users/tessa/scoop/apps/starship/1.9.1/starship.exe"

